name: "[MO] Rulare Matrice Anuala"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  sincronizare-monitoare:
    name: "Procesare An: ${{ matrix.an }}"
    runs-on: ubuntu-latest
    
    # Aici definim matricea de ani. GitHub va porni 4 rulari in paralel!
    strategy:
      fail-fast: false
      matrix:
        an: [2000,2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

    steps:
      - name: Descarcare cod
        uses: actions/checkout@v4

      - name: Configurare Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalare dependente
        run: |
          python -m pip install --upgrade pip
          pip install httpx google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Executare Script Universal
        run: |
          python -u sync_simple.py
        env:
          # Trimitem un singur an catre script din matricea YAML
          AN_CURENT: "${{ matrix.an }}"
          DRIVE_FOLDER_PDF: ${{ vars.DRIVE_FOLDER_PDF }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
